[package]
name = "v8_bytecode"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
v8_ast = { path = "../v8_ast" }
