[package]
name = "v8_lexer"
version = "0.1.0"
edition = "2021"
description = "Lexer for V8-Rust JavaScript engine"
license = "MIT"

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
criterion = "0.5"
serde_json = "1.0" 