[package]
name = "v8_parser"
version = "0.1.0"
edition = "2021"
description = "Parser for V8-Rust JavaScript engine"
license = "MIT"

[dependencies]
v8_lexer = { path = "../v8_lexer" }
v8_ast = { path = "../v8_ast" }
thiserror = "1.0"

[dev-dependencies]
criterion = "0.5" 